# Generated by Django 3.2.7 on 2021-10-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('judge', '0004_rename_case_id_judge_case'),
        ('Ncase', '0002_alter_new_case_case_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('room_number', models.IntegerField(blank=True, null=True)),
                ('datetime', models.DateTimeField()),
                ('case_id', models.ManyToManyField(to='Ncase.New_case')),
                ('judge_id', models.ManyToManyField(to='judge.judge')),
            ],
        ),
    ]
