# Generated by Django 3.2.7 on 2021-10-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0005_auto_20211028_0152'),
        ('court', '0005_alter_court_judge_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='judge_id',
            field=models.ManyToManyField(to='judge.Judge'),
        ),
    ]
