# Generated by Django 3.2.7 on 2021-10-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ncase', '0002_alter_new_case_case_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='police',
            fields=[
                ('police_id', models.IntegerField(primary_key=True, serialize=False)),
                ('police_name', models.CharField(max_length=50)),
                ('station_name', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=50)),
                ('new_case', models.ManyToManyField(to='Ncase.New_case')),
            ],
        ),
    ]
