# Generated by Django 3.2.7 on 2021-10-22 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='police',
            old_name='new_case',
            new_name='case_id',
        ),
    ]
