# Generated by Django 3.2.7 on 2021-10-22 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0005_police_case_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='police',
            name='case_id',
        ),
    ]
