# Generated by Django 3.2.7 on 2021-10-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0008_rename_new_case_id_police_case_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='police',
            name='police_id',
        ),
        migrations.AddField(
            model_name='police',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
