# Generated by Django 3.2.7 on 2021-10-22 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0009_auto_20211022_2344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='police',
        ),
    ]
