# Generated by Django 3.2.7 on 2021-10-22 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ncase', '0002_alter_new_case_case_date'),
        ('police', '0010_delete_police'),
    ]

    operations = [
        migrations.CreateModel(
            name='police',
            fields=[
                ('police_id', models.IntegerField(primary_key=True, serialize=False)),
                ('police_name', models.CharField(max_length=50)),
                ('post_name', models.CharField(max_length=50)),
                ('station_name', models.CharField(max_length=50)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ncase.new_case')),
            ],
        ),
    ]
