# Generated by Django 3.2.7 on 2021-10-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ncase', '0002_alter_new_case_case_date'),
        ('judge', '0004_rename_case_id_judge_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judge',
            name='case',
        ),
        migrations.AddField(
            model_name='judge',
            name='case_id',
            field=models.ManyToManyField(to='Ncase.New_case'),
        ),
    ]
