# Generated by Django 3.2.7 on 2021-10-26 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ncase', '0002_alter_new_case_case_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ncase.new_case')),
            ],
        ),
    ]
