# Generated by Django 3.2.7 on 2021-10-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('Solve', 'Solve'), ('Ranning', 'Ranning'), ('Dismiss', 'Dismiss')], max_length=50),
        ),
    ]
