# Generated by Django 3.2.7 on 2021-10-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New_case',
            fields=[
                ('case_id', models.IntegerField(primary_key=True, serialize=False)),
                ('case_name', models.CharField(max_length=50)),
                ('prose_name', models.CharField(max_length=50)),
                ('def_name', models.CharField(max_length=50)),
                ('case_date', models.DateField(max_length=50)),
            ],
        ),
    ]
