# Generated by Django 3.2.7 on 2021-10-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ncase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_case',
            name='case_date',
            field=models.DateField(),
        ),
    ]
