# Generated by Django 3.2.7 on 2021-10-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ncase', '0002_alter_new_case_case_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_case',
            name='case_id',
            field=models.IntegerField(auto_created=0, primary_key=True, serialize=False),
        ),
    ]
