# Generated by Django 3.2.7 on 2021-10-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ncase', '0002_alter_new_case_case_date'),
        ('lower', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='laywer',
            fields=[
                ('lower_id', models.IntegerField(primary_key=True, serialize=False)),
                ('lower_name', models.CharField(max_length=50)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('case_id', models.ManyToManyField(to='Ncase.New_case')),
            ],
        ),
        migrations.DeleteModel(
            name='lower',
        ),
    ]
