# Generated by Django 3.2.7 on 2021-10-23 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ncase', '0002_alter_new_case_case_date'),
        ('lower', '0002_auto_20211023_1208'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='laywer',
            new_name='Lower',
        ),
    ]
