# Generated by Django 3.2.7 on 2021-10-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lower', '0003_rename_laywer_lower'),
    ]

    operations = [
        migrations.AddField(
            model_name='lower',
            name='case_roll',
            field=models.CharField(choices=[('Defence', 'Defence '), ('prosecutor', 'prosecutor')], default='...', max_length=50),
        ),
    ]
