# Generated by Django 3.2.7 on 2021-10-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lower', '0004_lower_case_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lower',
            name='case_roll',
            field=models.CharField(choices=[('Defence', 'Defence '), ('Prosecutor', 'Prosecutor')], default='Defence', max_length=50),
        ),
    ]
